version: '3.4'

services:
  catalogdb:
    container_name: catalog_db
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 
  
  cartdb:
    container_name: cart_db
    restart: always
    ports:
      - "6379:6379" 

  discountdb:    
    container_name: discount_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Discounts
    restart: always
    ports:
      - "5432:5432"
    volumes:
      -  pg_data:/var/lib/postgresql/data

      
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data

  catalog.api:
    container_name: catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb 
    ports:
      - "8000:80"

  cart.api:
    container_name: cart_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis:Uri=cartdb:6379"
      - "DiscountServiceUri=http://discount.grpc"
    depends_on:
      - cartdb
    ports:
      - "8001:80"


  discount.api:
    container_name: discount_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgerServer=Server=discountdb;Port=5432;Database=Discounts;User Id=admin;Password=admin1234"
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgerServer=Server=discountdb;Port=5432;Database=Discounts;User Id=admin;Password=admin1234"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

